sudo: required
language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get build-dep libjlatexmath-java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
  - mvn cobertura:cobertura coveralls:report

addons:
  hosts:
    - jlmhost
  hostname: jlmhost
